# Site settings
title: Jeremy Jex
email: goat.farmer@gmail.com
url: https://github.com/Geitjeboer/JeremyJex.github.io#
description: "A data science with over a decade of teaching and healthcare experience. Also skilled in statistical modeling, machine learning, and data manipulation. Uses data science to improve client outcomes. Speaks Dutch, Spanish, Chinese, and French."
keywords: "Data Science, Healthcare, Statistical Analysis, Machine Learning, Data Wrangling, SQL, Python, SciKit Learn, Pandas, Spark, PySpark, Excel, Data Storytelling"
skills: "Data Science | Healthcare | Statistical Analysis | Machine Learning | Data Wrangling | SQL | Python | SciKit Learn | Pandas | Spark | PySpark | Excel | Data Storytelling"
meta_author: Jex Jeremy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF
  primary-rgb: "128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Linkedin
    url: https://www.linkedin.com/in/jeremy-jex/
  - title: github
    url: https://github.com/Geitjeboer

# Postal address (add as many lines as necessary)
address:
  - line: Olympia, WA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
